import { Development } from '../src/lib/types';

/** Publicly reported industry, patent, conference and company R&D — complements API harvests. */
export const CURATED_INDUSTRY: Development[] = [
  {
    id: 'ind-bovaer-eu-2024',
    title: 'EU Authorises Bovaer (3-NOP) Feed Additive for Dairy Cattle Methane Reduction',
    summary: 'The European Commission authorised DSM-Firmenich’s Bovaer (3-nitrooxypropanol) as a feed additive for dairy cows, following EFSA safety assessment. Trials show enteric methane cuts of ~30% with no adverse effects on milk yield or composition.',
    date: '2024-02-23',
    sourceUrl: 'https://www.dsm-firmenich.com/anh/news/bovaer.html',
    sourceName: 'DSM-Firmenich',
    function: 'Sustainability & Traceability',
    region: 'Europe',
    company: 'DSM-Firmenich',
    rdType: 'Product Launch',
    tags: ['methane', '3-NOP', 'feed additive'],
  },
  {
    id: 'ind-fonterra-amti-2024',
    title: 'Fonterra Scales On-Farm Methane Measurement Across New Zealand Supplier Herds',
    summary: 'Fonterra expanded farm-level methane and nitrogen efficiency measurement through its Co-operative Difference programme, pairing GreenFeed-style spot sampling with milk mid-infrared proxies to rank herds for low-emission genetics and feeding.',
    date: '2024-03-12',
    sourceUrl: 'https://www.fonterra.com',
    sourceName: 'Fonterra',
    function: 'Sustainability & Traceability',
    region: 'New Zealand',
    company: 'Fonterra',
    rdType: 'Industry News',
    tags: ['methane', 'MIR', 'co-op'],
  },
  {
    id: 'ind-arla-farmahead-2024',
    title: 'Arla Foods FarmAhead Check Becomes Mandatory Climate Tool for Farmer Owners',
    summary: 'Arla made FarmAhead Check the standard on-farm climate assessment for owner-members, covering feed, manure, energy and land use. Aggregated data feeds the co-op’s science-based targets and farmer incentive payments.',
    date: '2024-04-08',
    sourceUrl: 'https://www.arla.com',
    sourceName: 'Arla Foods',
    function: 'Sustainability & Traceability',
    region: 'Denmark',
    company: 'Arla',
    rdType: 'Product Launch',
    tags: ['LCA', 'farmer incentives', 'climate'],
  },
  {
    id: 'ind-gea-dairyrobot-r9500-2024',
    title: 'GEA DairyRobot R9500 Adds In-Line Cell Count and Automated Teat Spray',
    summary: 'GEA released a DairyRobot R9500 software and sensor pack with in-line somatic cell monitoring and adaptive teat-spray dosing, targeting mastitis detection during voluntary milking without extra labor.',
    date: '2024-05-14',
    sourceUrl: 'https://www.gea.com',
    sourceName: 'GEA',
    function: 'Engineering & Automation',
    region: 'Germany',
    company: 'GEA',
    rdType: 'Product Launch',
    tags: ['AMS', 'SCC', 'mastitis'],
  },
  {
    id: 'ind-delaval-vms-v300-2024',
    title: 'DeLaval VMS V300 Rollout Adds DeLaval Plus Herd Navigator Integration',
    summary: 'DeLaval bundled the VMS V300 voluntary milking system with Plus cloud analytics and Herd Navigator in-line progesterone, LDH and BHB sensing for fertility, mastitis and ketosis alerts.',
    date: '2024-06-03',
    sourceUrl: 'https://www.delaval.com',
    sourceName: 'DeLaval',
    function: 'Robotics & AI',
    region: 'Sweden',
    company: 'DeLaval',
    rdType: 'Product Launch',
    tags: ['VMS', 'ketosis', 'fertility'],
  },
  {
    id: 'ind-zoetis-clarifide-plus-2024',
    title: 'Zoetis Clarifide Plus Adds Wellness and Residual Feed Intake Indexes',
    summary: 'Zoetis expanded Clarifide Plus genomic testing for US Holsteins with wellness trait and residual feed intake indexes, letting herds select for health and feed efficiency alongside production.',
    date: '2024-01-18',
    sourceUrl: 'https://www.zoetisus.com',
    sourceName: 'Zoetis',
    function: 'Breeding & Genetics',
    region: 'USA',
    company: 'Zoetis',
    rdType: 'Product Launch',
    tags: ['genomics', 'RFI', 'wellness'],
  },
  {
    id: 'ind-genus-abs-sexcel-2024',
    title: 'Genus ABS Sexcel Sexed Semen Capacity Expansion in Wisconsin',
    summary: 'Genus ABS expanded Sexcel sex-sorted semen production in Wisconsin to meet dairy demand for heifer-focused breeding programs, citing improved conception rates versus earlier generation sexed products.',
    date: '2024-07-09',
    sourceUrl: 'https://www.absglobal.com',
    sourceName: 'ABS Global',
    function: 'Breeding & Genetics',
    region: 'USA',
    company: 'Genus',
    rdType: 'Industry News',
    tags: ['sexed semen', 'fertility'],
  },
  {
    id: 'ind-allflex-sensehub-2024',
    title: 'Allflex SenseHub Dairy Collar Gains Heat, Health and Rumination Alerts',
    summary: 'MSD Animal Health’s Allflex SenseHub dairy neck collar added combined heat detection, rumination drop and health-index alerts, positioning wearables as a substitute for visual observation in large freestall herds.',
    date: '2024-03-28',
    sourceUrl: 'https://www.allflex.global',
    sourceName: 'Allflex / MSD Animal Health',
    function: 'Digital Platforms & Innovation',
    region: 'Israel',
    company: 'Allflex',
    rdType: 'Product Launch',
    tags: ['wearable', 'rumination', 'heat detection'],
  },
  {
    id: 'ind-smaxtec-bolus-2024',
    title: 'smaXtec pH and Temperature Bolus Deployed for Subacute Ruminal Acidosis Watch',
    summary: 'smaXtec expanded its reticulum bolus network in Europe and North America, streaming rumen pH and inner-body temperature for SARA, calving and fever alerts into farm dashboards.',
    date: '2024-08-19',
    sourceUrl: 'https://smaxtec.com',
    sourceName: 'smaXtec',
    function: 'Animal Health',
    region: 'Austria',
    company: 'smaXtec',
    rdType: 'Technology Demo',
    tags: ['bolus', 'SARA', 'rumen pH'],
  },
  {
    id: 'ind-cattleeye-lameness-2024',
    title: 'CattleEye 2D Camera System Scores Locomotion Without Wearables',
    summary: 'CattleEye commercialised an overhead 2D camera plus computer-vision pipeline that scores dairy cow locomotion at the parlor exit, flagging early lameness without collars or pedometers.',
    date: '2024-09-04',
    sourceUrl: 'https://cattleeye.com',
    sourceName: 'CattleEye',
    function: 'Robotics & AI',
    region: 'UK',
    company: 'CattleEye',
    rdType: 'Product Launch',
    tags: ['computer vision', 'lameness'],
  },
  {
    id: 'ind-connecterra-ida-2024',
    title: 'Connecterra Ida Platform Adds Multi-Robot Herd Insights',
    summary: 'Connecterra’s Ida AI platform added cross-brand milking-robot data ingestion so mixed Lely/DeLaval/GEA barns can see unified fertility, health and feed-efficiency insights.',
    date: '2024-10-11',
    sourceUrl: 'https://www.connecterra.io',
    sourceName: 'Connecterra',
    function: 'Digital Platforms & Innovation',
    region: 'Netherlands',
    company: 'Connecterra',
    rdType: 'Product Launch',
    tags: ['AI', 'AMS', 'platform'],
  },
  {
    id: 'ind-perfect-day-whey-2024',
    title: 'Perfect Day Precision-Fermented Whey Reaches Additional CPG Formulations',
    summary: 'Perfect Day reported additional food-brand partnerships using animal-free beta-lactoglobulin produced in Trichoderma, targeting ice cream and protein beverages with dairy-identical functionality.',
    date: '2024-05-22',
    sourceUrl: 'https://perfectday.com',
    sourceName: 'Perfect Day',
    function: 'Product Development',
    region: 'USA',
    company: 'Perfect Day',
    rdType: 'Industry News',
    tags: ['precision fermentation', 'whey'],
  },
  {
    id: 'ind-remilk-israel-2024',
    title: 'Remilk Opens Industrial Precision-Fermentation Facility for Casein Proteins',
    summary: 'Israeli startup Remilk commissioned industrial-scale fermentation for bovine-identical dairy proteins, aiming at cheese and yogurt applications without livestock.',
    date: '2024-02-07',
    sourceUrl: 'https://www.remilk.com',
    sourceName: 'Remilk',
    function: 'Product Development',
    region: 'Israel',
    company: 'Remilk',
    rdType: 'Technology Demo',
    tags: ['casein', 'precision fermentation'],
  },
  {
    id: 'ind-formo-microbial-casein-2024',
    title: 'Formo (Germany) Advances Microbial Casein Cheese Prototypes',
    summary: 'Berlin-based Formo published progress on microbial casein for European-style cheeses, combining precision fermentation with traditional cheesemaking cultures.',
    date: '2024-11-06',
    sourceUrl: 'https://formo.bio',
    sourceName: 'Formo',
    function: 'Product Development',
    region: 'Germany',
    company: 'Formo',
    rdType: 'Technology Demo',
    tags: ['cheese', 'casein', 'fermentation'],
  },
  {
    id: 'ind-tetrapak-homogenizer-2024',
    title: 'Tetra Pak Launches Next-Gen Homogenizer Line for Energy-Efficient UHT Milk',
    summary: 'Tetra Pak introduced a homogenizer series claiming double-digit energy savings on UHT white milk lines, with digital condition monitoring for seals and pistons.',
    date: '2024-04-16',
    sourceUrl: 'https://www.tetrapak.com',
    sourceName: 'Tetra Pak',
    function: 'Dairy Processing',
    region: 'Sweden',
    company: 'Tetra Pak',
    rdType: 'Product Launch',
    tags: ['UHT', 'homogenizer', 'energy'],
  },
  {
    id: 'ind-spx-membrane-2024',
    title: 'SPX FLOW APV Membrane Skid Targets Whey Protein Isolate Yield',
    summary: 'SPX FLOW released an APV spiral-wound UF/DF skid configured for whey protein isolate, with automated CIP and flux-recovery analytics for cheese plants.',
    date: '2024-06-20',
    sourceUrl: 'https://www.spxflow.com',
    sourceName: 'SPX FLOW',
    function: 'Dairy Processing',
    region: 'USA',
    company: 'SPX Flow',
    rdType: 'Product Launch',
    tags: ['ultrafiltration', 'WPI', 'whey'],
  },
  {
    id: 'ind-novonesis-cultures-2024',
    title: 'Novonesis (Chr. Hansen + Novozymes) Unifies Dairy Culture and Enzyme Portfolio',
    summary: 'Following the Chr. Hansen–Novozymes combination, Novonesis packaged cheese cultures, adjuncts and coagulants under a single innovation roadmap for yield, flavor and phage robustness.',
    date: '2024-01-30',
    sourceUrl: 'https://www.novonesis.com',
    sourceName: 'Novonesis',
    function: 'Dairy Processing',
    region: 'Denmark',
    company: 'Novonesis',
    rdType: 'Industry News',
    tags: ['cultures', 'enzymes', 'cheese'],
  },
  {
    id: 'ind-kerry-taste-2024',
    title: 'Kerry Group Dairy Taste Modulation for Reduced-Sugar Yogurts',
    summary: 'Kerry launched taste-modulation systems for spoonable and drinkable yogurts, enabling sugar reduction while preserving dairy flavor and fermented-note balance.',
    date: '2024-09-17',
    sourceUrl: 'https://www.kerry.com',
    sourceName: 'Kerry Group',
    function: 'Product Development',
    region: 'Ireland',
    company: 'Kerry',
    rdType: 'Product Launch',
    tags: ['yogurt', 'sugar reduction'],
  },
  {
    id: 'ind-amul-solar-2024',
    title: 'GCMMF/Amul Pilots Solar-Powered BMC Clusters in Gujarat Villages',
    summary: 'Amul (GCMMF) piloted solar-assisted bulk milk coolers at village collection centres to cut diesel use and improve evening-milk quality during grid outages.',
    date: '2024-12-04',
    sourceUrl: 'https://amul.com',
    sourceName: 'Amul / GCMMF',
    function: 'Engineering & Automation',
    region: 'India',
    company: 'Amul',
    rdType: 'Technology Demo',
    tags: ['BMC', 'solar', 'cold chain'],
  },
  {
    id: 'ind-nddb-inaph-2024',
    title: 'NDDB INAPH Platform Expands AI-Assisted Disease and Breeding Records',
    summary: 'India’s National Dairy Development Board expanded Information Network for Animal Productivity and Health (INAPH) with mobile AI prompts for AI technicians covering heat, AI timing and calf registration.',
    date: '2024-08-01',
    sourceUrl: 'https://www.nddb.coop',
    sourceName: 'NDDB',
    function: 'Digital Platforms & Innovation',
    region: 'India',
    company: 'NDDB',
    institution: 'National Dairy Development Board',
    rdType: 'Industry News',
    tags: ['INAPH', 'breeding', 'extension'],
  },
  {
    id: 'ind-ndri-karnal-a2-2024',
    title: 'ICAR-NDRI Karnal Releases Protocol for Authenticated A2 Milk Testing',
    summary: 'ICAR-National Dairy Research Institute published a PCR and protein-based protocol for authenticating A2 (β-casein) milk in organised dairies, addressing adulteration and labelling disputes.',
    date: '2024-07-22',
    sourceUrl: 'https://ndri.res.in',
    sourceName: 'ICAR-NDRI',
    function: 'Quality & Food Safety',
    region: 'India',
    institution: 'ICAR-NDRI Karnal',
    rdType: 'Academic Study',
    tags: ['A2', 'authentication', 'PCR'],
  },
  {
    id: 'ind-embrapa-tropical-2024',
    title: 'Embrapa Dairy Cattle Releases Heat-Tolerance Indexes for Girolando',
    summary: 'Embrapa Gado de Leite published genomic heat-tolerance indexes for Girolando cattle, supporting breeding for milk yield under Brazilian tropical humidity.',
    date: '2024-11-19',
    sourceUrl: 'https://www.embrapa.br',
    sourceName: 'Embrapa',
    function: 'Breeding & Genetics',
    region: 'Brazil',
    institution: 'Embrapa Gado de Leite',
    rdType: 'Research Paper',
    tags: ['Girolando', 'heat tolerance'],
  },
  {
    id: 'ind-ilri-kenya-2024',
    title: 'ILRI and Kenyan Partners Trial Vaccine and Genetics Package for Smallholder Dairy',
    summary: 'The International Livestock Research Institute advanced combined East Coast fever vaccination, improved AI and feeding packages for Kenyan smallholder dairy, measuring milk yield and calf survival.',
    date: '2024-10-02',
    sourceUrl: 'https://www.ilri.org',
    sourceName: 'ILRI',
    function: 'Animal Health',
    region: 'Kenya',
    institution: 'ILRI',
    rdType: 'Clinical Trial',
    tags: ['ECF', 'smallholder', 'vaccine'],
  },
  {
    id: 'ind-teagasc-moorepark-2024',
    title: 'Teagasc Moorepark Grazing Platform Reports Multi-Year Nitrous Oxide Results',
    summary: 'Teagasc’s Moorepark research farm reported multi-year N2O emissions from rotational grazing dairy systems under different nitrogen rates and clover inclusion, informing Ireland’s climate roadmap.',
    date: '2024-05-08',
    sourceUrl: 'https://www.teagasc.ie',
    sourceName: 'Teagasc',
    function: 'Farm Management',
    region: 'Ireland',
    institution: 'Teagasc Moorepark',
    rdType: 'Research Paper',
    tags: ['grazing', 'N2O', 'clover'],
  },
  {
    id: 'ind-inrae-methane-2024',
    title: 'INRAE Publishes Genotype-by-Diet Effects on Enteric Methane in Holsteins',
    summary: 'INRAE researchers reported genotype-by-diet interactions for enteric methane in Holstein cows, arguing that methane breeding values should be interpreted alongside ration type.',
    date: '2024-09-25',
    sourceUrl: 'https://www.inrae.fr',
    sourceName: 'INRAE',
    function: 'Nutrition & Feeding',
    region: 'France',
    institution: 'INRAE',
    rdType: 'Research Paper',
    tags: ['methane', 'GxE', 'Holstein'],
  },
  {
    id: 'ind-agroscope-switzerland-2024',
    title: 'Agroscope Evaluates Alpine Pasture Effects on Milk Fatty Acid Profile',
    summary: 'Swiss Agroscope quantified how alpine versus lowland pasture changes milk CLA and omega-3 profiles, supporting PDO cheese differentiation and grassland dairy claims.',
    date: '2024-08-12',
    sourceUrl: 'https://www.agroscope.admin.ch',
    sourceName: 'Agroscope',
    function: 'Nutrition & Feeding',
    region: 'Switzerland',
    institution: 'Agroscope',
    rdType: 'Academic Study',
    tags: ['pasture', 'CLA', 'PDO'],
  },
  {
    id: 'ind-massey-once-a-day-2024',
    title: 'Massey University Once-a-Day Milking Trial Updates Labour and Yield Trade-offs',
    summary: 'Massey University reported updated once-a-day milking results for New Zealand seasonal herds, documenting labour savings versus milksolids loss and somatic cell implications.',
    date: '2024-12-11',
    sourceUrl: 'https://www.massey.ac.nz',
    sourceName: 'Massey University',
    function: 'Farm Management',
    region: 'New Zealand',
    institution: 'Massey University',
    rdType: 'Academic Study',
    tags: ['OAD milking', 'labour', 'milksolids'],
  },
  {
    id: 'ind-csiro-sensor-2024',
    title: 'CSIRO Walk-over-Weighing and RFID Package for Northern Dairy Herds',
    summary: 'CSIRO demonstrated walk-over-weighing plus RFID for tropical dairy systems, generating daily liveweight for heat-stress and nutrition decisions without race handling.',
    date: '2024-06-27',
    sourceUrl: 'https://www.csiro.au',
    sourceName: 'CSIRO',
    function: 'Digital Platforms & Innovation',
    region: 'Australia',
    institution: 'CSIRO',
    rdType: 'Technology Demo',
    tags: ['WOW', 'RFID', 'liveweight'],
  },
  {
    id: 'ind-uw-madison-calf-2024',
    title: 'UW–Madison Dairy Science Pair-Housing Calf Protocol Enters Extension Kits',
    summary: 'University of Wisconsin–Madison released extension kits for pair and small-group calf housing, summarising growth, health and social behaviour findings versus individual hutches.',
    date: '2024-03-05',
    sourceUrl: 'https://dysci.wisc.edu',
    sourceName: 'UW–Madison Dairy Science',
    function: 'Animal Welfare',
    region: 'USA',
    institution: 'University of Wisconsin–Madison',
    rdType: 'Conference',
    tags: ['calves', 'pair housing', 'welfare'],
  },
  {
    id: 'ind-cornell-pro-dairy-2024',
    title: 'Cornell PRO-DAIRY Releases Updated CNCPS Ration Model Guidance',
    summary: 'Cornell PRO-DAIRY published updated Cornell Net Carbohydrate and Protein System guidance for high-forage Northeastern rations, including methane and nitrogen excretion modules.',
    date: '2024-01-24',
    sourceUrl: 'https://cals.cornell.edu/pro-dairy',
    sourceName: 'Cornell PRO-DAIRY',
    function: 'Nutrition & Feeding',
    region: 'USA',
    institution: 'Cornell University',
    rdType: 'Academic Study',
    tags: ['CNCPS', 'ration', 'nitrogen'],
  },
  {
    id: 'ind-ucdavis-heat-2024',
    title: 'UC Davis Cattle Heat-Stress Index Linked to California Dairy Cooling Design',
    summary: 'UC Davis animal science and biological engineering teams linked THI-based heat-stress indexes to soaker and fan control setpoints for Central Valley freestall dairies.',
    date: '2024-07-16',
    sourceUrl: 'https://animalscience.ucdavis.edu',
    sourceName: 'UC Davis',
    function: 'Animal Welfare',
    region: 'USA',
    institution: 'UC Davis',
    rdType: 'Research Paper',
    tags: ['THI', 'cooling', 'heat stress'],
  },
  {
    id: 'ind-guelph-mastitis-2024',
    title: 'University of Guelph Dairy at Guelph Trials Selective Dry Cow Therapy Protocols',
    summary: 'Dairy at Guelph reported on-farm selective dry cow therapy protocols using SCC and culture, cutting dry-cow antibiotic use while tracking clinical mastitis in the next lactation.',
    date: '2024-11-13',
    sourceUrl: 'https://www.uoguelph.ca',
    sourceName: 'University of Guelph',
    function: 'Animal Health',
    region: 'Canada',
    institution: 'University of Guelph',
    rdType: 'Clinical Trial',
    tags: ['SDCT', 'antibiotic stewardship'],
  },
  {
    id: 'ind-reading-welfare-2024',
    title: 'University of Reading Cow-Calf Contact Systems Assessed for UK Dairies',
    summary: 'Reading researchers assessed cow-calf contact systems for UK dairies, measuring calf growth, cow milk yield, labour and public-acceptance implications versus early separation.',
    date: '2024-09-09',
    sourceUrl: 'https://www.reading.ac.uk',
    sourceName: 'University of Reading',
    function: 'Animal Welfare',
    region: 'UK',
    institution: 'University of Reading',
    rdType: 'Academic Study',
    tags: ['cow-calf', 'welfare'],
  },
  {
    id: 'ind-slusweden-feed-2024',
    title: 'SLU Uppsala Evaluates Nordic Red Methane and Feed Efficiency Breeding',
    summary: 'Swedish University of Agricultural Sciences evaluated combining residual methane and residual feed intake in Nordic Red breeding goals without large milk-yield trade-offs.',
    date: '2024-04-02',
    sourceUrl: 'https://www.slu.se',
    sourceName: 'SLU',
    function: 'Breeding & Genetics',
    region: 'Sweden',
    institution: 'Swedish University of Agricultural Sciences',
    rdType: 'Research Paper',
    tags: ['Nordic Red', 'RFI', 'methane'],
  },
  {
    id: 'ind-helsinki-valio-2024',
    title: 'University of Helsinki and Valio Pilot Carbo Farm Calculator 2.0',
    summary: 'Helsinki researchers and Valio piloted an updated farm carbon calculator covering peat soils, feed imports and manure management specific to Finnish dairy.',
    date: '2024-10-21',
    sourceUrl: 'https://www.helsinki.fi',
    sourceName: 'University of Helsinki / Valio',
    function: 'Sustainability & Traceability',
    region: 'Finland',
    company: 'Valio',
    institution: 'University of Helsinki',
    rdType: 'Technology Demo',
    tags: ['carbon calculator', 'peat'],
  },
  {
    id: 'ind-yili-china-2024',
    title: 'Yili Opens Smart Ranch Digital Twin for Inner Mongolia Mega-Dairies',
    summary: 'Inner Mongolia Yili launched a digital-twin ranch stack combining milking, feeding, environment and health sensors for mega-herd management and carbon reporting.',
    date: '2024-06-11',
    sourceUrl: 'https://www.yili.com',
    sourceName: 'Yili',
    function: 'Digital Platforms & Innovation',
    region: 'China',
    company: 'Yili',
    rdType: 'Product Launch',
    tags: ['digital twin', 'mega-dairy'],
  },
  {
    id: 'ind-mengniu-lab-2024',
    title: 'Mengniu Nutrition Lab Publishes HMO-Fortified Infant Formula Dairy Research',
    summary: 'Mengniu’s nutrition lab reported human-milk oligosaccharide fortification strategies in cow-milk infant formula, targeting gut microbiome outcomes in Chinese infants.',
    date: '2024-08-28',
    sourceUrl: 'https://www.mengniu.com',
    sourceName: 'Mengniu',
    function: 'Product Development',
    region: 'China',
    company: 'Mengniu',
    rdType: 'Research Paper',
    tags: ['HMO', 'infant formula'],
  },
  {
    id: 'ind-meiji-japan-2024',
    title: 'Meiji Probiotic Yogurt Strain Research Targets Immune Markers',
    summary: 'Meiji Holdings reported clinical work on proprietary Lactobacillus strains in yogurt for immune-marker modulation, expanding FOSHU-oriented dairy portfolios in Japan.',
    date: '2024-02-14',
    sourceUrl: 'https://www.meiji.com',
    sourceName: 'Meiji',
    function: 'Product Development',
    region: 'Japan',
    company: 'Meiji',
    rdType: 'Clinical Trial',
    tags: ['probiotic', 'yogurt', 'FOSHU'],
  },
  {
    id: 'ind-hokkaido-uni-2024',
    title: 'Hokkaido University Cold-Climate Barn Ventilation Model for Dairy Freestalls',
    summary: 'Hokkaido University modelled winter ventilation and ammonia in insulated dairy freestalls, recommending inlet and chimney configurations for northern Japan.',
    date: '2024-12-18',
    sourceUrl: 'https://www.hokudai.ac.jp',
    sourceName: 'Hokkaido University',
    function: 'Engineering & Automation',
    region: 'Japan',
    institution: 'Hokkaido University',
    rdType: 'Academic Study',
    tags: ['ventilation', 'ammonia', 'cold climate'],
  },
  {
    id: 'ind-inta-argentina-2024',
    title: 'INTA Argentina Grazing Dairy Systems Trial Silvopastoral Shade for Heat',
    summary: 'INTA evaluated silvopastoral shade trees in Argentine grazing dairies, measuring THI, milk yield and lying behaviour during summer heat waves.',
    date: '2024-01-11',
    sourceUrl: 'https://www.argentina.gob.ar/inta',
    sourceName: 'INTA',
    function: 'Farm Management',
    region: 'Argentina',
    institution: 'INTA',
    rdType: 'Academic Study',
    tags: ['silvopasture', 'heat', 'grazing'],
  },
  {
    id: 'ind-unam-mexico-2024',
    title: 'UNAM and Mexican Dairies Map Brucellosis Control in Dual-Purpose Herds',
    summary: 'UNAM veterinary researchers mapped Brucella control options for dual-purpose dairy-beef herds in tropical Mexico, combining vaccination, testing and milk-safety messaging.',
    date: '2024-05-30',
    sourceUrl: 'https://www.unam.mx',
    sourceName: 'UNAM',
    function: 'Quality & Food Safety',
    region: 'Mexico',
    institution: 'UNAM',
    rdType: 'Research Paper',
    tags: ['brucellosis', 'dual-purpose'],
  },
  {
    id: 'ind-up-southafrica-2024',
    title: 'University of Pretoria Trials Drought Rations for South African Dairy',
    summary: 'University of Pretoria animal science trials tested drought-year byproduct rations (hominy chop, soybean hulls) for Holstein herds, tracking milk yield and body condition.',
    date: '2024-03-19',
    sourceUrl: 'https://www.up.ac.za',
    sourceName: 'University of Pretoria',
    function: 'Nutrition & Feeding',
    region: 'South Africa',
    institution: 'University of Pretoria',
    rdType: 'Clinical Trial',
    tags: ['drought', 'byproducts'],
  },
  {
    id: 'ind-elanco-kexxtone-2024',
    title: 'Elanco Kexxtone Bolus Positioning Updated for Transition Cow Ketosis',
    summary: 'Elanco restated Kexxtone (monensin) controlled-release bolus guidance for transition dairy cows at risk of ketosis, pairing on-label use with BHB monitoring protocols.',
    date: '2024-04-24',
    sourceUrl: 'https://www.elanco.com',
    sourceName: 'Elanco',
    function: 'Animal Health',
    region: 'USA',
    company: 'Elanco',
    rdType: 'Industry News',
    tags: ['ketosis', 'transition cow'],
  },
  {
    id: 'ind-hipra-mastitis-vax-2024',
    title: 'HIPRA STARTVAC / Topvac Mastitis Vaccine Programs Expanded in Southern Europe',
    summary: 'HIPRA expanded mastitis vaccination programmes in Spain and Italy combining coliform and Staph. aureus components with dry-cow and milking hygiene SOPs.',
    date: '2024-09-02',
    sourceUrl: 'https://www.hipra.com',
    sourceName: 'HIPRA',
    function: 'Animal Health',
    region: 'Spain',
    company: 'HIPRA',
    rdType: 'Industry News',
    tags: ['vaccine', 'mastitis'],
  },
  {
    id: 'ind-boumatic-gemini-2024',
    title: 'BouMatic Gemini Milking Robot Gains US Dealer Network Expansion',
    summary: 'BouMatic expanded Gemini dual-box robot installations in the US Midwest, emphasising high-throughput robotic milking for 200–400 cow herds.',
    date: '2024-07-30',
    sourceUrl: 'https://boumatic.com',
    sourceName: 'BouMatic',
    function: 'Robotics & AI',
    region: 'USA',
    company: 'BouMatic',
    rdType: 'Product Launch',
    tags: ['robot', 'Midwest'],
  },
  {
    id: 'ind-fullwood-merlin-2024',
    title: 'Fullwood JOZ Merlin Robot Software Update for Grazing Herds',
    summary: 'Fullwood JOZ released Merlin software for seasonal grazing dairies, improving fetch-cow logic and pasture-access gates for Irish and UK robot herds.',
    date: '2024-05-06',
    sourceUrl: 'https://www.fullwoodjoz.com',
    sourceName: 'Fullwood JOZ',
    function: 'Robotics & AI',
    region: 'UK',
    company: 'Fullwood',
    rdType: 'Product Launch',
    tags: ['grazing', 'AMS'],
  },
  {
    id: 'ind-nedap-cowcontrol-2024',
    title: 'Nedap CowControl Integrates Heat Detection with Sorting Gates',
    summary: 'Nedap linked CowControl SmartTag data to automatic sorting gates so cows flagged for AI, vet check or lame trim are drafted without extra labour.',
    date: '2024-11-27',
    sourceUrl: 'https://www.nedap-livestockmanagement.com',
    sourceName: 'Nedap',
    function: 'Engineering & Automation',
    region: 'Netherlands',
    company: 'Nedap',
    rdType: 'Product Launch',
    tags: ['sorting gate', 'heat detection'],
  },
  {
    id: 'ind-cowmanager-ear-2024',
    title: 'CowManager Ear Sensor Adds Heat-Stress Module from Temperature Data',
    summary: 'CowManager added a heat-stress module using ear-sensor temperature and activity, alerting when cooling should be intensified in the holding pen and stalls.',
    date: '2024-08-07',
    sourceUrl: 'https://www.cowmanager.com',
    sourceName: 'CowManager',
    function: 'Animal Welfare',
    region: 'Netherlands',
    company: 'CowManager',
    rdType: 'Product Launch',
    tags: ['ear sensor', 'heat stress'],
  },
  {
    id: 'ind-trouw-feed-2024',
    title: 'Trouw Nutrition Selko IntelliBond and Methane-Additive Ration Packages',
    summary: 'Trouw Nutrition packaged hydroxy trace minerals with methane-mitigation feeding advice for dairy nutritionists, targeting both fertility and carbon intensity.',
    date: '2024-02-27',
    sourceUrl: 'https://www.trouwnutrition.com',
    sourceName: 'Trouw Nutrition',
    function: 'Nutrition & Feeding',
    region: 'Netherlands',
    company: 'Trouw Nutrition',
    rdType: 'Product Launch',
    tags: ['trace minerals', 'methane'],
  },
  {
    id: 'ind-adisseo-methionine-2024',
    title: 'Adisseo Smartamine MetaSmart Guidance for High-Producing Holsteins',
    summary: 'Adisseo updated metabolisable methionine recommendations for high-yielding Holsteins, linking amino-acid balance to milk protein and nitrogen efficiency.',
    date: '2024-06-05',
    sourceUrl: 'https://www.adisseo.com',
    sourceName: 'Adisseo',
    function: 'Nutrition & Feeding',
    region: 'France',
    company: 'Adisseo',
    rdType: 'Industry News',
    tags: ['methionine', 'milk protein'],
  },
  {
    id: 'ind-balchem-reashure-2024',
    title: 'Balchem ReaShure Choline Studies Highlight Transition Cow Outcomes',
    summary: 'Balchem highlighted new transition-cow datasets for rumen-protected choline (ReaShure), associating supplementation with lower ketosis risk and improved colostrum yield.',
    date: '2024-10-15',
    sourceUrl: 'https://www.balchem.com',
    sourceName: 'Balchem',
    function: 'Nutrition & Feeding',
    region: 'USA',
    company: 'Balchem',
    rdType: 'Clinical Trial',
    tags: ['choline', 'transition', 'colostrum'],
  },
  {
    id: 'ind-dfa-fairlife-2024',
    title: 'Dairy Farmers of America and fairlife Expand Ultra-Filtered Milk Capacity',
    summary: 'DFA-linked fairlife expanded ultra-filtered milk capacity, applying membrane processing to raise protein and cut sugar in branded fluid milk.',
    date: '2024-03-14',
    sourceUrl: 'https://www.dfamilk.com',
    sourceName: 'Dairy Farmers of America',
    function: 'Dairy Processing',
    region: 'USA',
    company: 'Dairy Farmers of America',
    rdType: 'Industry News',
    tags: ['ultrafiltered milk', 'protein'],
  },
  {
    id: 'ind-lactalis-italy-2024',
    title: 'Lactalis Invests in Grana Padano and Mozzarella Process Automation',
    summary: 'Lactalis announced process-automation upgrades in Italian PDO and mozzarella plants, including vision inspection and energy recovery on whey evaporators.',
    date: '2024-09-19',
    sourceUrl: 'https://www.lactalis.com',
    sourceName: 'Lactalis',
    function: 'Dairy Processing',
    region: 'Italy',
    company: 'Lactalis',
    rdType: 'Industry News',
    tags: ['PDO', 'mozzarella', 'automation'],
  },
  {
    id: 'ind-frieslandcampina-n2-2024',
    title: 'FrieslandCampina Foqus Future Planet Tightens On-Farm Nitrogen Rules',
    summary: 'FrieslandCampina’s Foqus planet programme tightened nitrogen and biodiversity criteria for member farms in the Netherlands, linking milk price extras to measured performance.',
    date: '2024-01-09',
    sourceUrl: 'https://www.frieslandcampina.com',
    sourceName: 'FrieslandCampina',
    function: 'Sustainability & Traceability',
    region: 'Netherlands',
    company: 'FrieslandCampina',
    rdType: 'Industry News',
    tags: ['nitrogen', 'milk price', 'biodiversity'],
  },
  {
    id: 'ind-glanbia-ireland-2024',
    title: 'Glanbia Ireland Rolls Out Milk Quality Rapid Test Network',
    summary: 'Glanbia Ireland expanded rapid antibiotic and SCC testing at intake, shortening tanker-hold times and improving residue-risk segregation.',
    date: '2024-07-03',
    sourceUrl: 'https://www.glanbiaireland.com',
    sourceName: 'Glanbia Ireland',
    function: 'Quality & Food Safety',
    region: 'Ireland',
    company: 'Glanbia',
    rdType: 'Product Launch',
    tags: ['antibiotics', 'intake testing'],
  },
  {
    id: 'ind-ornua-kerry-gold-2024',
    title: 'Ornua Research on Pasture-Fed Butter Fatty Acid Fingerprinting',
    summary: 'Ornua reported analytical work fingerprinting pasture-fed Irish butter fatty acids for origin claims and seasonal quality control of Kerrygold-style products.',
    date: '2024-05-21',
    sourceUrl: 'https://www.ornua.com',
    sourceName: 'Ornua',
    function: 'Quality & Food Safety',
    region: 'Ireland',
    company: 'Ornua',
    rdType: 'Academic Study',
    tags: ['butter', 'pasture-fed', 'authenticity'],
  },
  {
    id: 'ind-a2milk-anz-2024',
    title: 'The a2 Milk Company Expands Certified A2 Herd Testing in ANZ',
    summary: 'The a2 Milk Company expanded DNA testing of supplier herds in Australia and New Zealand to certify A2/A2 β-casein status for branded fresh milk.',
    date: '2024-08-14',
    sourceUrl: 'https://a2milk.com',
    sourceName: 'The a2 Milk Company',
    function: 'Breeding & Genetics',
    region: 'New Zealand',
    company: 'a2 Milk',
    rdType: 'Industry News',
    tags: ['A2', 'DNA testing'],
  },
  {
    id: 'ind-synlait-canterbury-2024',
    title: 'Synlait Lead With Pride Programme Adds Animal Welfare Audits',
    summary: 'Synlait’s Lead With Pride farm assurance added tighter animal-welfare audits covering lameness, body condition and calf management for infant-formula milk supply.',
    date: '2024-04-10',
    sourceUrl: 'https://www.synlait.com',
    sourceName: 'Synlait',
    function: 'Animal Welfare',
    region: 'New Zealand',
    company: 'Synlait',
    rdType: 'Industry News',
    tags: ['assurance', 'calves', 'infant formula'],
  },
  {
    id: 'ind-bega-australia-2024',
    title: 'Bega Cheese Upgrades Bega Valley Cheddar Plants for Energy Recovery',
    summary: 'Bega Cheese invested in heat-recovery and whey handling at Bega Valley cheddar plants, targeting Scope 1 energy cuts and higher whey-stream value.',
    date: '2024-12-02',
    sourceUrl: 'https://www.begagroup.com.au',
    sourceName: 'Bega Cheese',
    function: 'Dairy Processing',
    region: 'Australia',
    company: 'Bega',
    rdType: 'Industry News',
    tags: ['cheddar', 'energy recovery'],
  },
  {
    id: 'ind-saputo-canada-2024',
    title: 'Saputo Trials Water Reuse in Canadian Cheese Plants',
    summary: 'Saputo piloted condensate recovery and water-reuse loops in Canadian cheese facilities to cut municipal water intensity per tonne of product.',
    date: '2024-06-18',
    sourceUrl: 'https://www.saputo.com',
    sourceName: 'Saputo',
    function: 'Sustainability & Traceability',
    region: 'Canada',
    company: 'Saputo',
    rdType: 'Technology Demo',
    tags: ['water reuse', 'cheese plant'],
  },
  {
    id: 'ind-agropur-whey-2024',
    title: 'Agropur Expands Whey Protein Isolate Capacity in the US Midwest',
    summary: 'Agropur expanded WPI capacity, applying ion-exchange and filtration to serve sports-nutrition customers while valorising member-farm whey.',
    date: '2024-02-01',
    sourceUrl: 'https://www.agropur.com',
    sourceName: 'Agropur',
    function: 'Dairy Processing',
    region: 'USA',
    company: 'Agropur',
    rdType: 'Industry News',
    tags: ['WPI', 'whey'],
  },
  {
    id: 'ind-idf-wds-2024',
    title: 'IDF World Dairy Summit Sessions Spotlight Methane, AMR and Nutrition',
    summary: 'The International Dairy Federation World Dairy Summit convened science sessions on enteric methane, antimicrobial resistance in mastitis control, and dairy’s role in sustainable diets.',
    date: '2024-10-17',
    sourceUrl: 'https://worlddairysummit.org',
    sourceName: 'International Dairy Federation',
    function: 'Sustainability & Traceability',
    region: 'Global',
    rdType: 'Conference',
    tags: ['IDF', 'AMR', 'methane'],
  },
  {
    id: 'ind-adsa-2024',
    title: 'ADSA Annual Meeting 2024 Highlights Precision Livestock and Calf Immunity',
    summary: 'The American Dairy Science Association annual meeting featured packed sessions on precision livestock farming, calf passive immunity, and milk-MIR phenotyping for methane.',
    date: '2024-06-16',
    sourceUrl: 'https://www.adsa.org',
    sourceName: 'ADSA',
    function: 'Farm Management',
    region: 'USA',
    rdType: 'Conference',
    tags: ['ADSA', 'PLF', 'calves'],
  },
  {
    id: 'ind-eaap-2024',
    title: 'EAAP 2024 Dairy Genetics Commission Debates Methane Breeding Values',
    summary: 'The European Association for Animal Production dairy genetics commission debated how to publish and use enteric-methane breeding values across Holstein populations.',
    date: '2024-09-01',
    sourceUrl: 'https://www.eaap.org',
    sourceName: 'EAAP',
    function: 'Breeding & Genetics',
    region: 'Europe',
    rdType: 'Conference',
    tags: ['EAAP', 'breeding values'],
  },
  {
    id: 'ind-patent-ams-vision-2024',
    title: 'Patent Filing: Vision-Guided Teat Detection for Mixed-Breed AMS Herds',
    summary: 'A published patent application describes multi-camera teat detection robust to udder conformation differences in mixed Holstein-Jersey robot herds, reducing failed attachments.',
    date: '2024-03-21',
    sourceUrl: 'https://patents.google.com',
    sourceName: 'Patent literature',
    function: 'Robotics & AI',
    region: 'Global',
    rdType: 'Patent',
    tags: ['patent', 'teat detection', 'AMS'],
  },
  {
    id: 'ind-patent-methane-sensor-2024',
    title: 'Patent Filing: In-Parlor Sniffer for Individual Cow Methane Phenotyping',
    summary: 'A patent application covers a parlor-exit sniffer and algorithms to estimate individual-cow methane during milking for genetic evaluation at commercial scale.',
    date: '2024-11-08',
    sourceUrl: 'https://patents.google.com',
    sourceName: 'Patent literature',
    function: 'Sustainability & Traceability',
    region: 'Global',
    rdType: 'Patent',
    tags: ['patent', 'methane sniffer'],
  },
  {
    id: 'ind-patent-uf-cheese-2024',
    title: 'Patent Filing: Cold Ultrafiltration Pre-Concentration for Pasta Filata Cheese',
    summary: 'A process patent describes cold UF pre-concentration of milk for mozzarella/pasta filata, reducing vat energy and increasing moisture control.',
    date: '2024-05-02',
    sourceUrl: 'https://patents.google.com',
    sourceName: 'Patent literature',
    function: 'Dairy Processing',
    region: 'Italy',
    rdType: 'Patent',
    tags: ['patent', 'UF', 'mozzarella'],
  },
  {
    id: 'ind-boehringer-2025',
    title: 'Boehringer Ingelheim Dairy Respiratory Health Programme for Calves',
    summary: 'Boehringer Ingelheim expanded calf respiratory health programmes combining vaccination, colostrum QC and barn-air monitoring for dairy replacements.',
    date: '2025-01-15',
    sourceUrl: 'https://www.boehringer-ingelheim.com',
    sourceName: 'Boehringer Ingelheim',
    function: 'Animal Health',
    region: 'Germany',
    company: 'Boehringer Ingelheim',
    rdType: 'Industry News',
    tags: ['BRD', 'calves', 'vaccine'],
  },
  {
    id: 'ind-merck-ah-2025',
    title: 'Merck Animal Health SenseHub Dairy Analytics Dashboard 2025',
    summary: 'Merck Animal Health released a 2025 SenseHub dashboard with cohort comparisons for transition, reproduction and health events across multi-site dairies.',
    date: '2025-02-04',
    sourceUrl: 'https://www.merck-animal-health.com',
    sourceName: 'Merck Animal Health',
    function: 'Digital Platforms & Innovation',
    region: 'USA',
    company: 'Merck Animal Health',
    rdType: 'Product Launch',
    tags: ['SenseHub', 'dashboard'],
  },
  {
    id: 'ind-lely-vector-2025',
    title: 'Lely Vector Automatic Feeding System Gains Mixed-Ration Recipe AI',
    summary: 'Lely updated Vector automatic feeding with recipe optimisation that adjusts forage proportions from daily dry-matter and refusal data.',
    date: '2025-03-11',
    sourceUrl: 'https://www.lely.com',
    sourceName: 'Lely',
    function: 'Engineering & Automation',
    region: 'Netherlands',
    company: 'Lely',
    rdType: 'Product Launch',
    tags: ['Vector', 'TMR', 'feeding robot'],
  },
  {
    id: 'ind-delaval-plus-2025',
    title: 'DeLaval Plus Adds Open API for Third-Party Nutrition Models',
    summary: 'DeLaval Plus opened APIs so nutrition consultancies can pull milk, activity and robot-visit data into custom ration and health models.',
    date: '2025-04-02',
    sourceUrl: 'https://www.delaval.com',
    sourceName: 'DeLaval',
    function: 'Digital Platforms & Innovation',
    region: 'Sweden',
    company: 'DeLaval',
    rdType: 'Product Launch',
    tags: ['API', 'nutrition', 'cloud'],
  },
  {
    id: 'ind-gea-nyrpic-2025',
    title: 'GEA DairyProcessing Skid for ESL Milk with Reduced Heat Load',
    summary: 'GEA launched an ESL milk processing skid using gentler heat profiles and sterile filling interfaces aimed at 30–60 day refrigerated life.',
    date: '2025-05-20',
    sourceUrl: 'https://www.gea.com',
    sourceName: 'GEA',
    function: 'Dairy Processing',
    region: 'Germany',
    company: 'GEA',
    rdType: 'Product Launch',
    tags: ['ESL', 'heat treatment'],
  },
  {
    id: 'ind-dsm-bovaer-uk-2025',
    title: 'UK Dairy Processors Begin Bovaer Supplier Incentive Schemes',
    summary: 'After UK authorisation, several processors launched farmer incentives for Bovaer inclusion, with mass-balance Scope 3 claims under development.',
    date: '2025-01-28',
    sourceUrl: 'https://www.dsm-firmenich.com',
    sourceName: 'DSM-Firmenich',
    function: 'Sustainability & Traceability',
    region: 'UK',
    company: 'DSM-Firmenich',
    rdType: 'Industry News',
    tags: ['Bovaer', 'Scope 3', 'incentives'],
  },
  {
    id: 'ind-crv-feedxplore-2025',
    title: 'CRV FeedExcel Index Rolled Out for More European Holstein Markets',
    summary: 'CRV expanded FeedExcel, a breeding index for milk per kg of dry matter, into additional European markets using mid-infrared and intake research herds.',
    date: '2025-02-18',
    sourceUrl: 'https://www.crv4all.com',
    sourceName: 'CRV',
    function: 'Breeding & Genetics',
    region: 'Netherlands',
    company: 'CRV',
    rdType: 'Product Launch',
    tags: ['FeedExcel', 'efficiency'],
  },
  {
    id: 'ind-semex-immunity-2025',
    title: 'Semex Immunity+ Marketing Packs Updated Genomic Health Traits',
    summary: 'Semex refreshed Immunity+ sire marketing with updated mastitis, metritis and calf-survival genomic health traits for North American dairies.',
    date: '2025-03-06',
    sourceUrl: 'https://www.semex.com',
    sourceName: 'Semex',
    function: 'Breeding & Genetics',
    region: 'Canada',
    company: 'Semex',
    rdType: 'Industry News',
    tags: ['Immunity+', 'genomic health'],
  },
  {
    id: 'ind-alltech-yea-sacc-2025',
    title: 'Alltech Yea-Sacc Dairy Trials Published for Heat-Stress Rations',
    summary: 'Alltech released trial summaries of Yea-Sacc live yeast in heat-stress dairy rations, reporting rumen pH stability and milk-fat outcomes.',
    date: '2025-06-03',
    sourceUrl: 'https://www.alltech.com',
    sourceName: 'Alltech',
    function: 'Nutrition & Feeding',
    region: 'USA',
    company: 'Alltech',
    rdType: 'Clinical Trial',
    tags: ['yeast', 'heat stress', 'rumen'],
  },
  {
    id: 'ind-cargill-digit-2025',
    title: 'Cargill Dairy Enteligen Digital Nutrition Advisor Enters More Countries',
    summary: 'Cargill expanded Enteligen-style digital dairy nutrition tools that recommend ration changes from milk components, forage tests and cow-group data.',
    date: '2025-04-22',
    sourceUrl: 'https://www.cargill.com',
    sourceName: 'Cargill',
    function: 'Digital Platforms & Innovation',
    region: 'USA',
    company: 'Cargill',
    rdType: 'Product Launch',
    tags: ['digital nutrition', 'rations'],
  },
  {
    id: 'ind-adm-silage-2025',
    title: 'ADM Pioneer-Linked Silage Inoculant Range for High-Moisture Corn',
    summary: 'ADM promoted silage inoculant packages for high-moisture corn and alfalfa, targeting aerobic stability and dairy TMR heating in bunkers.',
    date: '2025-07-08',
    sourceUrl: 'https://www.adm.com',
    sourceName: 'ADM',
    function: 'Nutrition & Feeding',
    region: 'USA',
    company: 'ADM',
    rdType: 'Product Launch',
    tags: ['silage', 'inoculant'],
  },
  {
    id: 'ind-danone-regen-2025',
    title: 'Danone Regenerative Dairy Pilot Reports Soil and Biodiversity KPIs',
    summary: 'Danone published first-wave regenerative dairy pilot KPIs covering soil organic matter, hedgerows and reduced synthetic N on supplier farms in Europe and the US.',
    date: '2025-05-13',
    sourceUrl: 'https://www.danone.com',
    sourceName: 'Danone',
    function: 'Sustainability & Traceability',
    region: 'France',
    company: 'Danone',
    rdType: 'Industry News',
    tags: ['regenerative', 'soil'],
  },
  {
    id: 'ind-nestle-netzero-2025',
    title: 'Nestlé Dairy Net-Zero Roadmap Adds On-Farm Feed and Manure Levers',
    summary: 'Nestlé updated its dairy net-zero roadmap with quantified levers for feed additives, manure methane and animal-efficiency genetics in key sourcing regions.',
    date: '2025-03-25',
    sourceUrl: 'https://www.nestle.com',
    sourceName: 'Nestlé',
    function: 'Sustainability & Traceability',
    region: 'Switzerland',
    company: 'Nestlé',
    rdType: 'Industry News',
    tags: ['net zero', 'manure', 'feed'],
  },
  {
    id: 'ind-emmi-switzerland-2025',
    title: 'Emmi Climate Stewardship Programme Pays Alpine Dairy Farmers for Measures',
    summary: 'Emmi expanded climate-stewardship payments to Swiss alpine and lowland dairy farmers for feed, energy and biodiversity actions verified by Agroscope methods.',
    date: '2025-06-17',
    sourceUrl: 'https://www.emmi.com',
    sourceName: 'Emmi',
    function: 'Sustainability & Traceability',
    region: 'Switzerland',
    company: 'Emmi',
    rdType: 'Industry News',
    tags: ['incentives', 'alpine dairy'],
  },
  {
    id: 'ind-valio-carbo-2025',
    title: 'Valio Carbo Farm Tools Opened to More Finnish Producer Co-ops',
    summary: 'Valio opened Carbo farm calculation tools to additional Finnish producer groups, standardising farm-gate carbon intensity for milk pricing discussions.',
    date: '2025-02-11',
    sourceUrl: 'https://www.valio.com',
    sourceName: 'Valio',
    function: 'Digital Platforms & Innovation',
    region: 'Finland',
    company: 'Valio',
    rdType: 'Product Launch',
    tags: ['carbon intensity', 'pricing'],
  },
  {
    id: 'ind-polmlek-poland-2025',
    title: 'Polish Dairies Invest in Lactose-Free UHT Lines for Export',
    summary: 'Polish processors including Polmlek-linked plants invested in enzymatic lactose-free UHT lines targeting Middle East and Asian export specifications.',
    date: '2025-07-22',
    sourceUrl: 'https://www.polmlek.com',
    sourceName: 'Polmlek',
    function: 'Dairy Processing',
    region: 'Poland',
    company: 'Polmlek',
    rdType: 'Industry News',
    tags: ['lactose-free', 'UHT', 'export'],
  },
  {
    id: 'ind-korea-seoulmilk-2025',
    title: 'Seoul Milk Cooperative Trials Smart Farm CCTV Lameness Scoring',
    summary: 'Seoul Milk cooperative farms trialled CCTV plus computer vision for lameness scoring in high-cost land Korean freestalls, aiming to cut vet lag time.',
    date: '2025-04-09',
    sourceUrl: 'https://www.seoulmilk.co.kr',
    sourceName: 'Seoul Milk',
    function: 'Robotics & AI',
    region: 'South Korea',
    company: 'Seoul Milk',
    rdType: 'Technology Demo',
    tags: ['CCTV', 'lameness', 'Korea'],
  },
  {
    id: 'ind-ethiopia-ilri-2025',
    title: 'Ethiopia Dairy Development Partners Scale Milk Safety Training with ILRI',
    summary: 'Ethiopian dairy development partners with ILRI scaled milk-safety and cooling training for informal-to-formal market transitions in peri-urban Addis catchments.',
    date: '2025-01-21',
    sourceUrl: 'https://www.ilri.org',
    sourceName: 'ILRI',
    function: 'Quality & Food Safety',
    region: 'Ethiopia',
    institution: 'ILRI',
    rdType: 'Conference',
    tags: ['informal market', 'milk safety'],
  },
  {
    id: 'ind-uganda-dairydvp-2025',
    title: 'Uganda Dairy Development Traces Milk with Mobile QR at Collection Centres',
    summary: 'Ugandan collection centres piloted QR-based milk traceability from farmer can to cooler, aiming to reduce adulteration complaints in Kampala retail.',
    date: '2025-08-05',
    sourceUrl: 'https://www.agriculture.go.ug',
    sourceName: 'Uganda Dairy Development',
    function: 'Sustainability & Traceability',
    region: 'Uganda',
    rdType: 'Technology Demo',
    tags: ['QR', 'traceability', 'adulteration'],
  },
  {
    id: 'ind-pakistan-uvas-2025',
    title: 'UVAS Lahore Mastitis Pathogen Survey Informs Dry-Cow Therapy Policy',
    summary: 'University of Veterinary and Animal Sciences Lahore published a mastitis pathogen survey informing selective dry-cow therapy discussions for Pakistani peri-urban dairies.',
    date: '2025-03-18',
    sourceUrl: 'https://uvas.edu.pk',
    sourceName: 'UVAS Lahore',
    function: 'Animal Health',
    region: 'Pakistan',
    institution: 'UVAS Lahore',
    rdType: 'Academic Study',
    tags: ['mastitis', 'SDCT', 'Pakistan'],
  },
  {
    id: 'ind-bangladesh-bldp-2025',
    title: 'Bangladesh Livestock Research Institute Trials Urea-Molasses Blocks for Dairy',
    summary: 'BLRI trialled urea-molasses multinutrient blocks for smallholder dairy in fodder-scarce seasons, measuring milk yield and cost per litre.',
    date: '2025-05-27',
    sourceUrl: 'https://www.blri.gov.bd',
    sourceName: 'BLRI',
    function: 'Nutrition & Feeding',
    region: 'Bangladesh',
    institution: 'Bangladesh Livestock Research Institute',
    rdType: 'Clinical Trial',
    tags: ['UMMB', 'smallholder'],
  },
  {
    id: 'ind-vietnam-thmilk-2025',
    title: 'TH Milk Mega-Farm in Nghe An Adds Robotic Milking and Cooling Upgrades',
    summary: 'TH True Milk reported robotic milking and energy-efficient cooling upgrades at Nghe An mega-farms supplying UHT brands across Vietnam.',
    date: '2025-06-24',
    sourceUrl: 'https://www.thmilk.vn',
    sourceName: 'TH True Milk',
    function: 'Engineering & Automation',
    region: 'Vietnam',
    company: 'TH True Milk',
    rdType: 'Industry News',
    tags: ['mega-farm', 'UHT', 'robots'],
  },
  {
    id: 'ind-idfa-amr-2025',
    title: 'IDFA and NMPF Issue Updated US Dairy Antimicrobial Stewardship Guidance',
    summary: 'US dairy trade groups updated antimicrobial stewardship guidance covering mastitis, metritis and calf diarrhoea, aligning with FDA VFD and residue-prevention rules.',
    date: '2025-07-15',
    sourceUrl: 'https://www.idfa.org',
    sourceName: 'IDFA / NMPF',
    function: 'Animal Health',
    region: 'USA',
    rdType: 'Industry News',
    tags: ['AMR', 'stewardship', 'VFD'],
  },
  {
    id: 'ind-fao-leap-2025',
    title: 'FAO LEAP Updates Dairy GHG Quantification Guidelines',
    summary: 'FAO Livestock Environmental Assessment and Performance partnership updated dairy GHG quantification guidelines, tightening enteric methane and manure modules for national inventories.',
    date: '2025-04-16',
    sourceUrl: 'https://www.fao.org/partnerships/leap',
    sourceName: 'FAO LEAP',
    function: 'Sustainability & Traceability',
    region: 'Global',
    institution: 'FAO',
    rdType: 'Academic Study',
    tags: ['LEAP', 'GHG', 'inventory'],
  },
  {
    id: 'ind-ifcn-2025',
    title: 'IFCN Dairy Report 2025 Benchmarks Cost of Production Across 100+ Regions',
    summary: 'The IFCN Dairy Research Network 2025 report benchmarked cost of milk production, labour productivity and typical-farm carbon metrics across more than 100 dairy regions.',
    date: '2025-09-10',
    sourceUrl: 'https://ifcndairy.org',
    sourceName: 'IFCN',
    function: 'Farm Management',
    region: 'Global',
    rdType: 'Conference',
    tags: ['benchmarking', 'cost of production'],
  },
  {
    id: 'ind-world-dairy-expo-2025',
    title: 'World Dairy Expo 2025 Showcases Methane Additives and Vision Lameness Tech',
    summary: 'World Dairy Expo in Madison highlighted commercial methane additives, vision lameness systems, and next-gen genomic indexes across the trade-show floor.',
    date: '2025-09-30',
    sourceUrl: 'https://worlddairyexpo.com',
    sourceName: 'World Dairy Expo',
    function: 'Farm Management',
    region: 'USA',
    rdType: 'Conference',
    tags: ['WDE', 'trade show'],
  },
  {
    id: 'ind-space-france-2025',
    title: 'SPACE Rennes 2025 Dairy Hall Focuses on Robot Grazing and Low-Emission Buildings',
    summary: 'SPACE agricultural show in Rennes featured French dairy robotics for grazing systems and low-emission building designs under national methane plans.',
    date: '2025-09-16',
    sourceUrl: 'https://www.space.fr',
    sourceName: 'SPACE',
    function: 'Engineering & Automation',
    region: 'France',
    rdType: 'Conference',
    tags: ['SPACE', 'grazing robots'],
  },
  {
    id: 'ind-eurotier-2024',
    title: 'EuroTier 2024 Gold Medal Concepts for Dairy Emission and Welfare Sensors',
    summary: 'DLG EuroTier 2024 awarded dairy concepts spanning barn-emission sensors, cow-traffic optimisation and welfare cameras, signalling 2025 commercial launches.',
    date: '2024-11-12',
    sourceUrl: 'https://www.eurotier.com',
    sourceName: 'EuroTier / DLG',
    function: 'Engineering & Automation',
    region: 'Germany',
    rdType: 'Conference',
    tags: ['EuroTier', 'sensors'],
  },
  {
    id: 'ind-imagindairy-2025',
    title: 'Imagindairy Receives Regulatory Progress for Animal-Free Dairy Proteins',
    summary: 'Imagindairy reported regulatory and scale-up progress for animal-free dairy proteins produced via precision fermentation, targeting cream cheese and ice-cream applications.',
    date: '2025-02-25',
    sourceUrl: 'https://imagindairy.com',
    sourceName: 'Imagindairy',
    function: 'Product Development',
    region: 'Israel',
    company: 'Imagindairy',
    rdType: 'Industry News',
    tags: ['precision fermentation', 'regulatory'],
  },
  {
    id: 'ind-turtletree-2025',
    title: 'TurtleTree Precision-Fermented Lactoferrin Moves Toward Food Applications',
    summary: 'TurtleTree advanced precision-fermented lactoferrin toward food and nutrition applications, positioning bovine-identical bioactive proteins without livestock extraction.',
    date: '2025-05-06',
    sourceUrl: 'https://turtletree.com',
    sourceName: 'TurtleTree',
    function: 'Product Development',
    region: 'Singapore',
    company: 'TurtleTree',
    rdType: 'Technology Demo',
    tags: ['lactoferrin', 'bioactive'],
  },
  {
    id: 'ind-john-deere-2025',
    title: 'John Deere See & Spray Adjacent Tech Explored for Dairy Forage Weeds',
    summary: 'John Deere and partners discussed computer-vision weed targeting in alfalfa and corn silage ground serving dairy rations, aiming to cut herbicide use.',
    date: '2025-04-29',
    sourceUrl: 'https://www.deere.com',
    sourceName: 'John Deere',
    function: 'Farm Management',
    region: 'USA',
    company: 'John Deere',
    rdType: 'Technology Demo',
    tags: ['See & Spray', 'forage'],
  },
  {
    id: 'ind-trimble-dairy-2025',
    title: 'Trimble Precision Ag Stack Tied to Dairy Forage Harvest Logistics',
    summary: 'Trimble connected yield mapping and harvest logistics to dairy forage inventories so nutritionists can track bunker filling by field and hybrid.',
    date: '2025-06-10',
    sourceUrl: 'https://www.trimble.com',
    sourceName: 'Trimble',
    function: 'Digital Platforms & Innovation',
    region: 'USA',
    company: 'Trimble',
    rdType: 'Product Launch',
    tags: ['yield map', 'silage'],
  },
  {
    id: 'ind-afimilk-afilab-2025',
    title: 'Afimilk AfiLab In-Line Milk Lab Adds Fatty-Acid and Blood-in-Milk Flags',
    summary: 'Afimilk enhanced AfiLab in-line milk analysis with fatty-acid and blood-in-milk flags, giving parlor-level alerts for ketosis risk and teat injury.',
    date: '2025-08-12',
    sourceUrl: 'https://www.afimilk.com',
    sourceName: 'Afimilk',
    function: 'Quality & Food Safety',
    region: 'Israel',
    company: 'Afimilk',
    rdType: 'Product Launch',
    tags: ['in-line', 'fatty acids', 'blood'],
  },
  {
    id: 'ind-pennstate-extension-2025',
    title: 'Penn State Extension Rolls Out Robotic Milking Labor Benchmarks',
    summary: 'Penn State Extension published labor and fetch-cow benchmarks for robotic dairies in Pennsylvania, helping farms decide AMS versus parlor reinvestment.',
    date: '2025-01-08',
    sourceUrl: 'https://extension.psu.edu',
    sourceName: 'Penn State Extension',
    function: 'Farm Management',
    region: 'USA',
    institution: 'Penn State University',
    rdType: 'Academic Study',
    tags: ['labor', 'AMS', 'benchmarks'],
  },
  {
    id: 'ind-minnesota-manure-2025',
    title: 'University of Minnesota Manure Digester Co-op Model for Midwest Dairies',
    summary: 'University of Minnesota researchers modelled multi-farm manure digester co-ops for Midwest dairies, covering RNG offtake, nutrients and community acceptance.',
    date: '2025-07-01',
    sourceUrl: 'https://extension.umn.edu',
    sourceName: 'University of Minnesota',
    function: 'Sustainability & Traceability',
    region: 'USA',
    institution: 'University of Minnesota',
    rdType: 'Research Paper',
    tags: ['RNG', 'digester', 'manure'],
  },
  {
    id: 'ind-illinois-calf-2025',
    title: 'University of Illinois Automated Calf Feeder Behaviour as Disease Predictor',
    summary: 'Illinois researchers showed that drinking-speed and visit patterns on automated calf feeders predict BRD 24–48 hours before clinical scoring.',
    date: '2025-08-19',
    sourceUrl: 'https://aces.illinois.edu',
    sourceName: 'University of Illinois',
    function: 'Animal Health',
    region: 'USA',
    institution: 'University of Illinois',
    rdType: 'Research Paper',
    tags: ['calf feeder', 'BRD', 'behaviour'],
  },
];
