import { Development } from '../src/lib/types';

/** Curated milk & milk-product marketing — launches, campaigns, packaging, advertising, social media. */
export const CURATED_MARKETING: Development[] = [
  {
    id: 'mkt-amul-topical-ads-2024',
    title: 'Amul Continues Topical Billboard and Print Campaigns for Milk and Butter Brands',
    summary:
      'GCMMF (Amul) sustained its iconic topical advertising across India — tying butter and milk brand messaging to news events, sports and culture. The cooperative’s in-house creative team produces daily print and outdoor ads that reinforce Amul as India’s leading dairy brand.',
    date: '2024-06-15',
    sourceUrl: 'https://brandequity.economictimes.indiatimes.com',
    sourceName: 'ET BrandEquity',
    function: 'Marketing',
    region: 'India',
    company: 'Amul',
    rdType: 'Industry News',
    tags: ['advertising', 'topical ads', 'India', 'butter', 'milk'],
  },
  {
    id: 'mkt-kerrygold-make-it-gold-2024',
    title: 'Kerrygold Launches “Make It Gold” UK Advertising Campaign for Butter and Cheese',
    summary:
      'Ornua’s Kerrygold rolled out a multi-channel “Make It Gold” campaign in the UK, spanning TV, digital and in-store POS to defend premium butter and cheddar share against private label and Irish competitors.',
    date: '2024-03-20',
    sourceUrl: 'https://en.edairynews.com',
    sourceName: 'eDairyNews',
    function: 'Marketing',
    region: 'UK',
    company: 'Ornua',
    rdType: 'Product Launch',
    tags: ['advertising', 'butter', 'cheese', 'UK', 'campaign'],
  },
  {
    id: 'mkt-tetra-pak-plant-based-cap-2024',
    title: 'Tetra Pak Introduces Plant-Based Caps and Linked Packaging for UHT Milk Cartons',
    summary:
      'Tetra Pak launched plant-based caps tied to certified carton packaging for UHT milk, targeting retailer and brand-owner sustainability claims on shelf. Early adopters include European and Asian dairy brands seeking lower-carbon packaging stories.',
    date: '2024-04-10',
    sourceUrl: 'https://www.tetrapak.com',
    sourceName: 'Tetra Pak',
    function: 'Marketing',
    region: 'Global',
    company: 'Tetra Pak',
    rdType: 'Product Launch',
    tags: ['packaging', 'sustainability', 'UHT milk', 'carton'],
  },
  {
    id: 'mkt-chobani-coffee-creamer-2024',
    title: 'Chobani Expands Coffee Creamer Line with Seasonal Flavours and Retail Media Push',
    summary:
      'Chobani added limited-edition coffee creamer SKUs and paired the launches with targeted retail media and social content, positioning the brand beyond Greek yogurt into everyday milk-based beverages.',
    date: '2024-08-22',
    sourceUrl: 'https://www.dairyreporter.com',
    sourceName: 'DairyReporter',
    function: 'Marketing',
    region: 'USA',
    company: 'Chobani',
    rdType: 'Product Launch',
    tags: ['product launch', 'creamer', 'retail media', 'social media'],
  },
  {
    id: 'mkt-mother-dairy-fresh-2024',
    title: 'Mother Dairy Highlights Farm-to-Fridge Fresh Milk Positioning in Delhi-NCR Campaign',
    summary:
      'Mother Dairy reinforced its “fresh milk within hours” narrative through in-store activations, metro branding and digital video in Delhi-NCR — competing with regional cooperatives and national UHT brands on trust and cold-chain freshness.',
    date: '2024-05-08',
    sourceUrl: 'https://www.motherdairy.com',
    sourceName: 'Mother Dairy',
    function: 'Marketing',
    region: 'India',
    company: 'Mother Dairy',
    rdType: 'Industry News',
    tags: ['fresh milk', 'India', 'campaign', 'retail'],
  },
  {
    id: 'mkt-a2-milk-brand-2024',
    title: 'a2 Milk Company Invests in Brand Advertising to Rebuild US Shelf Presence',
    summary:
      'The a2 Milk Company increased US brand media spend and in-store sampling to explain A1/A2 protein differentiation, aiming to recover distribution after category slowdown — focusing purely on cow’s milk and related dairy beverages.',
    date: '2024-02-14',
    sourceUrl: 'https://www.a2milk.com',
    sourceName: 'a2 Milk Company',
    function: 'Marketing',
    region: 'USA',
    company: 'a2 Milk',
    rdType: 'Industry News',
    tags: ['brand', 'advertising', 'milk', 'USA'],
  },
  {
    id: 'mkt-danone-activia-gut-2024',
    title: 'Danone Activia Gut Health Campaign Links Yogurt to Everyday Wellness on Social',
    summary:
      'Danone ran a global Activia campaign pairing microbiome education with influencer-led recipe content on Instagram and TikTok, repositioning yogurt as a daily gut-health ritual rather than a dessert substitute.',
    date: '2024-07-01',
    sourceUrl: 'https://www.danone.com',
    sourceName: 'Danone',
    function: 'Marketing',
    region: 'Global',
    company: 'Danone',
    rdType: 'Industry News',
    tags: ['yogurt', 'social media', 'influencer', 'wellness'],
  },
  {
    id: 'mkt-nestle-munchk-ins-2024',
    title: 'Nestlé India Promotes Munch and Milkmaid Through Festive Integrated Campaigns',
    summary:
      'Nestlé India combined TV, e-commerce bundles and creator partnerships for condensed milk (Milkmaid) and dairy confectionery during festive seasons — a benchmark for dairy-adjacent FMCG marketing in India’s milk-product aisle.',
    date: '2024-10-05',
    sourceUrl: 'https://www.nestle.in',
    sourceName: 'Nestlé India',
    function: 'Marketing',
    region: 'India',
    company: 'Nestlé',
    rdType: 'Industry News',
    tags: ['India', 'festive', 'condensed milk', 'FMCG'],
  },
  {
    id: 'mkt-arla-lactofree-2024',
    title: 'Arla LactoFREE Uses In-Store Taste Trials to Grow Lactose-Free Milk Share in Europe',
    summary:
      'Arla Foods scaled LactoFREE sampling and allergen-clear shelf talkers across EU retailers, converting lactose-intolerant shoppers to branded milk rather than plant drinks — a trade-marketing play in the fresh milk category.',
    date: '2024-09-12',
    sourceUrl: 'https://www.arla.com',
    sourceName: 'Arla Foods',
    function: 'Marketing',
    region: 'Europe',
    company: 'Arla',
    rdType: 'Industry News',
    tags: ['lactose-free', 'milk', 'in-store', 'Europe'],
  },
  {
    id: 'mkt-sig-combibloc-2024',
    title: 'SIG Combibloc ESG-Linked Packaging Wins Dairy Brand Owner Adoption in Asia',
    summary:
      'SIG promoted combibloc ESG-linked packaging — connecting cartons to verified carbon or forest projects — helping Asian UHT milk brands communicate sustainability on-pack and in digital campaigns without changing liquid recipes.',
    date: '2024-11-18',
    sourceUrl: 'https://www.sig.biz',
    sourceName: 'SIG',
    function: 'Marketing',
    region: 'Asia',
    rdType: 'Product Launch',
    tags: ['packaging innovation', 'UHT milk', 'ESG', 'Asia'],
  },
  {
    id: 'mkt-fairlife-ultra-filtered-2024',
    title: 'Fairlife Ultra-Filtered Milk Doubles Down on Protein Messaging in US Sports Marketing',
    summary:
      'Coca-Cola-owned Fairlife expanded athlete partnerships and gym-channel placements for ultra-filtered milk, emphasising higher protein and lower sugar versus conventional white milk — distinct from meat or sports-nutrition powders.',
    date: '2024-06-28',
    sourceUrl: 'https://fairlife.com',
    sourceName: 'Fairlife',
    function: 'Marketing',
    region: 'USA',
    company: 'Fairlife',
    rdType: 'Industry News',
    tags: ['protein milk', 'sports marketing', 'USA'],
  },
  {
    id: 'mkt-yili-ambassador-china-2024',
    title: 'Yili Milk Uses Celebrity Brand Ambassadors and Winter Sports Tie-Ins in China',
    summary:
      'Yili, China’s largest dairy group, renewed celebrity ambassador contracts and sponsored winter-sports content to anchor liquid milk and yogurt brands with national pride narratives — a scale reference for dairy marketing in Asia.',
    date: '2024-01-25',
    sourceUrl: 'https://www.yili.com',
    sourceName: 'Yili Group',
    function: 'Marketing',
    region: 'China',
    company: 'Yili',
    rdType: 'Industry News',
    tags: ['brand ambassador', 'China', 'milk', 'yogurt'],
  },
  {
    id: 'mkt-packaging-dairy-strategic-2025',
    title: 'Packaging Becomes Strategic Marketing Asset for Global Dairy Brands',
    summary:
      'Industry analysis shows dairy companies treating packaging — recyclable cartons, tethered caps, on-pack QR provenance — as front-line marketing tools to win retailer listings and justify price premiums on milk, yogurt and cheese.',
    date: '2025-02-10',
    sourceUrl: 'https://dairynews.today',
    sourceName: 'DairyNews.today',
    function: 'Marketing',
    region: 'Global',
    rdType: 'Industry News',
    tags: ['packaging innovation', 'market strategy', 'sustainability'],
  },
  {
    id: 'mkt-parag-milk-foods-india-2024',
    title: 'Parag Milk Foods Promotes Go Cheese and Gowardhan Ghee via Regional TV and Digital',
    summary:
      'Parag Milk Foods pushed Go cheese snacking formats and Gowardhan ghee through Marathi and Hindi digital video plus modern-trade displays — illustrating regional dairy brand building beyond national cooperatives in India.',
    date: '2024-08-05',
    sourceUrl: 'https://www.paragmilkfoods.com',
    sourceName: 'Parag Milk Foods',
    function: 'Marketing',
    region: 'India',
    company: 'Parag',
    rdType: 'Industry News',
    tags: ['cheese', 'ghee', 'India', 'regional marketing'],
  },
  {
    id: 'mkt-tillamook-campaign-2024',
    title: 'Tillamook Cooperative Runs “Dairy Done Right” US Campaign for Cheese and Ice Cream',
    summary:
      'Tillamook’s farmer-owned cooperative campaign highlighted coastal Oregon dairy heritage across streaming TV and social, supporting cheese and ice cream lines — explicitly milk-product focused with no meat adjacency.',
    date: '2024-04-25',
    sourceUrl: 'https://www.tillamook.com',
    sourceName: 'Tillamook',
    function: 'Marketing',
    region: 'USA',
    rdType: 'Industry News',
    tags: ['cheese', 'ice cream', 'co-op', 'advertising'],
  },
];
